# Datasource properties
spring:
  datasource:
# Hikari properties
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 100

# Active profile
  profiles:
    active: local

  # Hibernate(JPA) properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Enable ANSI color support in terminal for logs
  output:
    ansi:
      enabled: always

# CORS properties
cors:
  allowed-methods: "GET,POST,PATCH,PUT,OPTIONS,DELETE"
  allowed-headers: "Authorization,Content-Type,X-XSRF-TOKEN,ACCEPT"
  exposed-headers: "Authorization"

# JWT Token properties (Custom)
application:
  security:
    jwt:
      issuer: TheWildOasis
      secret-key: Q1d4NjBZY1RjbEY4djNLVGRENHZKc2h5NGNqOXhoRlM4NWM2MnlINGFPbXF1ekw4VXgrOE9RZzU0NU5sdzJZcw==
      expiration: 86400000 # a day (86400000)
      refresh-token:
        expiration: 604800000 # 7 days (604800000)
        cookie-name: REFRESH-TOKEN
      request-header-name: "Authorization"


# AWS Region
aws:
  region: ap-south-1
  s3:
    bucket: wild-oasis


# Logging
logging:
  file:
    name: logs/WildOasis.log
  level:
    root: info
    com.thewildoasis: debug

